#!/usr/bin/env python3
"""Deterministic bench dataset generator.

Produces:
  data-a.sql / data-b.sql          — INSERT statements only
  init-mysql-a.sql / init-mysql-b.sql / init-postgres.sql
                                   — schema.sql + matching data (compose mounts)

Datasets A (series=11) and B (series=22) share schema and row *counts* but
differ in customer/product/order values so E3 can prove tool manifests are
config-driven, not data-driven.

Regenerate with:
  python3 bench/db/generate_data.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
ORDER_COUNT = 2000
CUSTOMER_COUNT = 40
PRODUCT_COUNT = 25
STATUSES = ("completed", "cancelled", "pending", "refunded")
COUNTRIES = ("US", "GB", "IN", "DE", "BR", "NA")


class LCG:
    """Minimal deterministic PRNG so regenerating the files is bit-stable."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next(self) -> int:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

    def randint(self, lo: int, hi: int) -> int:
        return lo + (self.next() % (hi - lo + 1))

    def choice(self, seq):
        return seq[self.next() % len(seq)]

    def money(self, lo_cents: int, hi_cents: int) -> str:
        cents = self.randint(lo_cents, hi_cents)
        return f"{cents / 100:.2f}"


def emit_data(series: int, label: str) -> str:
    rng = LCG(seed=series * 10007 + 17)
    lines: list[str] = [
        f"-- Data set '{label}'. Same schema as the other instance, different rows.",
        f"-- Generated by generate_data.py (series={series}, orders={ORDER_COUNT}).",
        "",
        "INSERT INTO customers (id,name,email,country_code) VALUES",
    ]
    cust_rows = []
    for i in range(1, CUSTOMER_COUNT + 1):
        cc = rng.choice(COUNTRIES)
        cust_rows.append(
            f"({i},'Customer {series}-{i}','c{i}@ex{series}.test','{cc}')"
        )
    lines.append(",\n".join(cust_rows) + ";")
    lines.append("")
    lines.append("INSERT INTO products (id,sku,name,price) VALUES")
    prod_rows = []
    for i in range(1, PRODUCT_COUNT + 1):
        price = rng.money(100, 99999)
        prod_rows.append(
            f"({i},'SKU-{series}-{i:04d}','Product {series}-{i}',{price})"
        )
    lines.append(",\n".join(prod_rows) + ";")
    lines.append("")
    lines.append("INSERT INTO orders (id,customer_id,status,total,placed_at) VALUES")
    order_rows = []
    for i in range(1, ORDER_COUNT + 1):
        cid = rng.randint(1, CUSTOMER_COUNT)
        status = rng.choice(STATUSES)
        total = rng.money(100, 249999)
        order_rows.append(f"({i},{cid},'{status}',{total},NULL)")
    lines.append(",\n".join(order_rows) + ";")
    lines.append("")
    lines.append(
        "INSERT INTO internal_audit (id,actor,action) VALUES "
        "(1,'system','bootstrap');"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    schema = (ROOT / "schema.sql").read_text()
    data_a = emit_data(11, "a")
    data_b = emit_data(22, "b")

    (ROOT / "data-a.sql").write_text(data_a)
    (ROOT / "data-b.sql").write_text(data_b)

    # Compose mounts these init scripts; keep them in sync with data-*.sql.
    (ROOT / "init-mysql-a.sql").write_text(schema.rstrip() + "\n\n" + data_a)
    (ROOT / "init-mysql-b.sql").write_text(schema.rstrip() + "\n\n" + data_b)
    # Postgres reuses dataset A (cross-db experiment compares engines, not A vs B).
    (ROOT / "init-postgres.sql").write_text(schema.rstrip() + "\n\n" + data_a)

    print(f"Wrote data-a.sql / data-b.sql with {ORDER_COUNT} orders each")
    print("Wrote init-mysql-a.sql / init-mysql-b.sql / init-postgres.sql")


if __name__ == "__main__":
    main()
